module.exports = {
  someSidebar: {
    "Desarrollo de Software": ["software-development-resources","what-is-a-developer", "ux-design-insights"],
    "Frontend": ["frontend-resources"],
    "W2S (Where to Start)": ["github-actions-w2s"],
    "Backend": ["wip-alert","backend-project-setup", "backend-resources"],
    "Vida": [
      "comprar-casa-merida",
      "quotes-i-like",
      "seeking-wisdom",
      "better-thinking"
    ],
    "Aprendizajes": [
      "aprendizajes-marzo-2021"
    ],
    "Book Notes": [{
      type: 'autogenerated',
      dirName: 'book-notes',
    }]
  },
};
